### ISSUE TITLE
Fails to run for Python 3.9

### ISSUE THREAD

**Issue by patrick-stephens** [viralpoetry/kubesurveyor#1]
Does not seem to work for me on MacOS Big Sur with Python 3.9 and everything installed via `brew`.

```
brew install graphviz
pip3 install kubesurveyor
```
```
kubesurveyor default           
Traceback (most recent call last):
  File "/usr/local/bin/kubesurveyor", line 8, in <module>
    sys.exit(parse_args())
  File "/usr/local/lib/python3.9/site-packages/kubesurveyor/main.py", line 362, in parse_args
    main(args)
  File "/usr/local/lib/python3.9/site-packages/kubesurveyor/main.py", line 272, in main
    viz_dot = visualize()
  File "/usr/local/lib/python3.9/site-packages/kubesurveyor/main.py", line 203, in visualize
    label=proto,
UnboundLocalError: local variable 'proto' referenced before assignment
```

```
pip3 --version
pip 21.1.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
cat /usr/local/bin/kubesurveyor
#!/usr/local/opt/python@3.9/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from kubesurveyor.main import parse_args
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(parse_args())

```

**Comment by viralpoetry** [comment]
@patrick-stephens thank you for reporting this. It's actually uninitialized `proto` (for example `http`) value that is scrapped from ingress, but this time it's  used as a label for the edge between service and pod. I will fix it

**Comment by viralpoetry** [comment]
I have updated version to 1.0.1 and will add proper `proto` in other pull request.
